export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
export const UPDATE_SEARCH_RESULT = "UPDATE_SEARCH_RESULT";
export const UPDATE_SELECTED_CATEGORY = "UPDATE_SELECTED_CATEGORY";
export const UPDATE_SELECTED_RATING = "UPDATE_SELECTED_RATING";
export const UPDATE_MAP_COORDS = "UPDATE_MAP_COORDS";
export const UPDATE_USER_COORDS = "UPDATE_USER_COORDS";
export const UPDATE_SHOW_MAP = "UPDATE_SHOW_MAP";
